# Generated by Django 5.2.5 on 2026-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("laptop", "Laptop"),
                    ("phone", "Phone"),
                    ("accessories", "Accessories"),
                ],
                default="laptop",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
