# Generated by Django 5.2.5 on 2026-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(default="https://via.placeholder.com/300"),
            preserve_default=False,
        ),
    ]
