# Generated by Django 5.2.5 on 2026-03-12 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0002_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product")},
        ),
    ]
